"""initial migration

Revision ID: 7c4fea76a3b2
Revises: 810f0567bd30
Create Date: 2022-07-05 13:54:19.974572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4fea76a3b2'
down_revision = '810f0567bd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('details', sa.Text(), nullable=True))
    op.drop_column('product', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('product', 'details')
    # ### end Alembic commands ###
